/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import java.net.URLDecoder;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.pojo.Dxzhaopin;
import com.service.DxzhaopinService;
import com.struts.form.DxzhaopinForm;
import com.util.Page;
import com.util.PageUtil;
import com.util.StringUtil;

/** 
 * MyEclipse Struts
 * Creation date: 04-29-2016
 * 
 * XDoclet definition:
 * @struts.action path="/dxzhaopin" name="dxzhaopinForm" input="/form/dxzhaopin.jsp" scope="request" validate="true"
 */
public class DxzhaopinAction extends DispatchAction {
	private DxzhaopinService dxzhaopinService;
	public DxzhaopinService getDxzhaopinService() {
		return dxzhaopinService;
	}
	public void setDxzhaopinService(DxzhaopinService dxzhaopinService) {
		this.dxzhaopinService = dxzhaopinService;
	}
	
	
	// 通过action  method方式添加dxzhaopin
		public ActionForward dxzhaopinAddExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			DxzhaopinForm dxzhaopinForm = (DxzhaopinForm) form;// TODO Auto-generated method stub
			Dxzhaopin user=new Dxzhaopin();
			user.setTitle(dxzhaopinForm.getTitle());
			user.setContent(dxzhaopinForm.getContent());
			user.setCydw(dxzhaopinForm.getCydw());
			user.setAddtime(StringUtil.getTimestampFromDate(new Date()));
			user.setLooknum(0);  //浏览量
			dxzhaopinService.dxzhaopinAdd(user);
			return mapping.findForward("dxzhaopinFind");  //成功
		}
		
		// 通过action  method方式删除dxzhaopin
		public ActionForward dxzhaopinDeleteExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			String dxzhaopinid=request.getParameter("dxzhaopinid");
			Dxzhaopin user=dxzhaopinService.dxzhaopinByID(new Integer(dxzhaopinid));
			dxzhaopinService.dxzhaopinDelete(user);
			
			String findinfo=request.getParameter("findinfo");
			if(findinfo!=null)
				findinfo=URLDecoder.decode(findinfo,"UTF-8");
			else
				findinfo="";
			
			String pagenumber=request.getParameter("pagenumber");
			if(pagenumber==null) pagenumber="1";
			Page p=PageUtil.createPage(10,dxzhaopinService.findNumsByLikeNameOrId(findinfo),new Integer(pagenumber));
			request.getSession().setAttribute("pagenumber",p.getCurrentPage());
			request.getSession().setAttribute("maxpagenumber",p.getTotalPage());
			request.getSession().setAttribute("dxzhaopinlist",dxzhaopinService.dxzhaopinLikeNameOrId(findinfo,p));  //设置session
			return mapping.findForward("dxzhaopinMana");  //成功
		}
		
		// 通过action  method方式修改dxzhaopin之前
		public ActionForward dxzhaopinBeforeModifyExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			String dxzhaopinid=request.getParameter("dxzhaopinid");
			Dxzhaopin item=dxzhaopinService.dxzhaopinByID(Integer.parseInt(dxzhaopinid));
			request.getSession().setAttribute("dxzhaopinmodifyinfo",item);  //设置session
			return mapping.findForward("dxzhaopinBeforeModify");  //成功
		}
		
		// 通过action  method方式修改dxzhaopin
		public ActionForward dxzhaopinModifyExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			DxzhaopinForm dxzhaopinForm = (DxzhaopinForm) form;// TODO Auto-generated method stub
			String dxzhaopinid=request.getParameter("dxzhaopinid");
			Dxzhaopin user=dxzhaopinService.dxzhaopinByID(new Integer(dxzhaopinid));
			user.setTitle(dxzhaopinForm.getTitle());
			user.setContent(dxzhaopinForm.getContent());
			user.setCydw(dxzhaopinForm.getCydw());
			dxzhaopinService.dxzhaopinModify(user);
			return mapping.findForward("dxzhaopinFind");  //成功
		}
		
		
		// 通过action  method方式  获取所有dxzhaopin
		public ActionForward dxzhaopinFindExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			
			DxzhaopinForm dxzhaopinForm = (DxzhaopinForm) form;// TODO Auto-generated method stub
			//decode一次
			String findinfo=request.getParameter("findinfo");
			if(findinfo!=null)
				findinfo=URLDecoder.decode(findinfo,"UTF-8");
			else
				findinfo="";
			request.getSession().setAttribute("findinfo",findinfo);
			
			String pagenumber=request.getParameter("pagenumber");
			if(pagenumber==null) pagenumber="1";
			Page p=PageUtil.createPage(10,dxzhaopinService.findNumsByLikeNameOrId(findinfo),new Integer(pagenumber));
			
			request.getSession().setAttribute("pagenumber",p.getCurrentPage());
			request.getSession().setAttribute("maxpagenumber",p.getTotalPage());
			request.getSession().setAttribute("dxzhaopinlist",dxzhaopinService.dxzhaopinLikeNameOrId(findinfo,p));  //设置session
			return mapping.findForward("dxzhaopinMana");  //成功
		}
		
		//招聘信息查看
		public ActionForward dxzhaopinInfoLookExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			String dxzhaopinid=request.getParameter("dxzhaopinid");
			Dxzhaopin item=dxzhaopinService.dxzhaopinByID(Integer.parseInt(dxzhaopinid));
			item.setLooknum(item.getLooknum()+1);
			dxzhaopinService.dxzhaopinModify(item);
			item.setCydw(item.getCydw().replaceAll("\n", "<br>"));
			request.getSession().setAttribute("dxzhaopininfolook",item);  //设置session
			return mapping.findForward("dxzhaopinInfoLook");  //成功
		}
}