/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import java.net.URLDecoder;
import java.util.Date;
import java.util.Iterator;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.pojo.Ptzhaopin;
import com.pojo.Teacher;
import com.service.PtzhaopinService;
import com.struts.form.PtzhaopinForm;
import com.struts.form.PtzhaopinForm;
import com.util.Page;
import com.util.PageUtil;
import com.util.StringUtil;

/** 
 * MyEclipse Struts
 * Creation date: 04-28-2016
 * 
 * XDoclet definition:
 * @struts.action path="/puzhaopin" name="puzhaopinForm" input="/form/puzhaopin.jsp" scope="request" validate="true"
 */
public class PtzhaopinAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	private PtzhaopinService ptzhaopinService;
	public PtzhaopinService getPtzhaopinService() {
		return ptzhaopinService;
	}
	public void setPtzhaopinService(PtzhaopinService ptzhaopinService) {
		this.ptzhaopinService = ptzhaopinService;
	}
	
	
	// 通过action  method方式添加ptzhaopin
		public ActionForward ptzhaopinAddExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			PtzhaopinForm ptzhaopinForm = (PtzhaopinForm) form;// TODO Auto-generated method stub
			Ptzhaopin user=new Ptzhaopin();
			user.setName(ptzhaopinForm.getName());
			user.setTitle(ptzhaopinForm.getTitle());
			user.setPhone(ptzhaopinForm.getPhone());
			user.setEmail(ptzhaopinForm.getEmail());
			user.setChuanzhen(ptzhaopinForm.getChuanzhen());
			user.setShenfe(ptzhaopinForm.getShenfe());
			user.setXingzhi(ptzhaopinForm.getXingzhi());
			user.setHangye(ptzhaopinForm.getHangye());
			user.setAddress(ptzhaopinForm.getAddress());
			user.setHomeurl(ptzhaopinForm.getHomeurl());
			user.setZpaddr(ptzhaopinForm.getZpaddr());
			user.setStarttime(StringUtil.getTimestampFromDate(StringUtil.getDateTimeFromString(ptzhaopinForm.getStarttime())));
			user.setEndtime(StringUtil.getTimestampFromDate(StringUtil.getDateTimeFromString(ptzhaopinForm.getEndtime())));
			user.setDwdescr(ptzhaopinForm.getDwdescr());
			user.setGangwei(ptzhaopinForm.getGangwei());
			user.setXueli(ptzhaopinForm.getXueli());
			user.setZhuanye(ptzhaopinForm.getZhuanye());
			user.setNums(ptzhaopinForm.getNums());
			user.setGangweidescr(ptzhaopinForm.getGangweidescr());
			user.setAddtime(StringUtil.getTimestampFromDate(new Date()));
			user.setLooksnum(0);  //浏览量
			ptzhaopinService.ptzhaopinAdd(user);
			return mapping.findForward("ptzhaopinFind");  //成功
		}
		
		// 通过action  method方式删除ptzhaopin
		public ActionForward ptzhaopinDeleteExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			String ptzhaopinid=request.getParameter("ptzhaopinid");
			Ptzhaopin user=ptzhaopinService.ptzhaopinByID(new Integer(ptzhaopinid));
			ptzhaopinService.ptzhaopinDelete(user);
			
			String findinfo=request.getParameter("findinfo");
			if(findinfo!=null)
				findinfo=URLDecoder.decode(findinfo,"UTF-8");
			else
				findinfo="";
			
			String pagenumber=request.getParameter("pagenumber");
			if(pagenumber==null) pagenumber="1";
			Page p=PageUtil.createPage(10,ptzhaopinService.findNumsByLikeNameOrId(findinfo),new Integer(pagenumber));
			request.getSession().setAttribute("pagenumber",p.getCurrentPage());
			request.getSession().setAttribute("maxpagenumber",p.getTotalPage());
			request.getSession().setAttribute("ptzhaopinlist",ptzhaopinService.ptzhaopinLikeNameOrId(findinfo,p));  //设置session
			return mapping.findForward("ptzhaopinMana");  //成功
		}
		
		// 通过action  method方式修改ptzhaopin之前
		public ActionForward ptzhaopinBeforeModifyExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			String ptzhaopinid=request.getParameter("ptzhaopinid");
			Ptzhaopin item=ptzhaopinService.ptzhaopinByID(Integer.parseInt(ptzhaopinid));
			request.getSession().setAttribute("ptzhaopinmodifyinfo",item);  //设置session
			return mapping.findForward("ptzhaopinBeforeModify");  //成功
		}
		
		// 通过action  method方式修改ptzhaopin
		public ActionForward ptzhaopinModifyExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			PtzhaopinForm ptzhaopinForm = (PtzhaopinForm) form;// TODO Auto-generated method stub
			String ptzhaopinid=request.getParameter("ptzhaopinid");
			Ptzhaopin user=ptzhaopinService.ptzhaopinByID(new Integer(ptzhaopinid));
			user.setName(ptzhaopinForm.getName());
			user.setTitle(ptzhaopinForm.getTitle());
			user.setPhone(ptzhaopinForm.getPhone());
			user.setEmail(ptzhaopinForm.getEmail());
			user.setChuanzhen(ptzhaopinForm.getChuanzhen());
			user.setShenfe(ptzhaopinForm.getShenfe());
			user.setHangye(ptzhaopinForm.getHangye());
			user.setXingzhi(ptzhaopinForm.getXingzhi());
			user.setAddress(ptzhaopinForm.getAddress());
			user.setHomeurl(ptzhaopinForm.getHomeurl());
			user.setZpaddr(ptzhaopinForm.getZpaddr());
			user.setStarttime(StringUtil.getTimestampFromDate(StringUtil.getDateTimeFromString(ptzhaopinForm.getStarttime())));
			user.setEndtime(StringUtil.getTimestampFromDate(StringUtil.getDateTimeFromString(ptzhaopinForm.getEndtime())));
			user.setDwdescr(ptzhaopinForm.getDwdescr());
			user.setGangwei(ptzhaopinForm.getGangwei());
			user.setXueli(ptzhaopinForm.getXueli());
			user.setZhuanye(ptzhaopinForm.getZhuanye());
			user.setNums(ptzhaopinForm.getNums());
			user.setGangweidescr(ptzhaopinForm.getGangweidescr());
			ptzhaopinService.ptzhaopinModify(user);
			return mapping.findForward("ptzhaopinFind");  //成功
		}
		
		
		// 通过action  method方式  获取所有ptzhaopin
		public ActionForward ptzhaopinFindExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			
			PtzhaopinForm ptzhaopinForm = (PtzhaopinForm) form;// TODO Auto-generated method stub
			//decode一次
			String findinfo=request.getParameter("findinfo");
			if(findinfo!=null)
				findinfo=URLDecoder.decode(findinfo,"UTF-8");
			else
				findinfo="";
			request.getSession().setAttribute("findinfo",findinfo);
			
			String pagenumber=request.getParameter("pagenumber");
			if(pagenumber==null) pagenumber="1";
			Page p=PageUtil.createPage(10,ptzhaopinService.findNumsByLikeNameOrId(findinfo),new Integer(pagenumber));
			
			request.getSession().setAttribute("pagenumber",p.getCurrentPage());
			request.getSession().setAttribute("maxpagenumber",p.getTotalPage());
			request.getSession().setAttribute("ptzhaopinlist",ptzhaopinService.ptzhaopinLikeNameOrId(findinfo,p));  //设置session
			return mapping.findForward("ptzhaopinMana");  //成功
		}
		
		//招聘信息查看
		public ActionForward ptzhaopinInfoLookExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			String ptzhaopinid=request.getParameter("ptzhaopinid");
			Ptzhaopin item=ptzhaopinService.ptzhaopinByID(Integer.parseInt(ptzhaopinid));
			item.setLooksnum(item.getLooksnum()+1);
			ptzhaopinService.ptzhaopinModify(item);
			item.setDwdescr(item.getDwdescr().replaceAll("\n", "<br>"));
			request.getSession().setAttribute("ptzhaopininfolook",item);  //设置session
			return mapping.findForward("ptzhaopinInfoLook");  //成功
		}
}