/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import java.net.URLDecoder;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.pojo.Dxzhaopin;
import com.pojo.Gonggao;
import com.pojo.Ptzhaopin;
import com.service.DxzhaopinService;
import com.service.GonggaoService;
import com.service.PtzhaopinService;
import com.struts.form.DxzhaopinForm;
import com.struts.form.PtzhaopinForm;
import com.util.Page;
import com.util.PageUtil;

/** 
 * MyEclipse Struts
 * Creation date: 05-17-2016
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class QiantaiAction extends DispatchAction {
	private DxzhaopinService dxzhaopinService;
	public DxzhaopinService getDxzhaopinService() {
		return dxzhaopinService;
	}
	public void setDxzhaopinService(DxzhaopinService dxzhaopinService) {
		this.dxzhaopinService = dxzhaopinService;
	}
	private GonggaoService gonggaoService;
	public GonggaoService getGonggaoService() {
		return gonggaoService;
	}
	public void setGonggaoService(GonggaoService gonggaoService) {
		this.gonggaoService = gonggaoService;
	}
	private PtzhaopinService ptzhaopinService;
	public PtzhaopinService getPtzhaopinService() {
		return ptzhaopinService;
	}
	public void setPtzhaopinService(PtzhaopinService ptzhaopinService) {
		this.ptzhaopinService = ptzhaopinService;
	}
	
	//qiantaiHomeExecute前台首页
	// 通过action  method方式  获取所有ptzhaopin
	public ActionForward qiantaiHomeExecute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		
		PtzhaopinForm ptzhaopinForm = (PtzhaopinForm) form;// TODO Auto-generated method stub
		request.getSession().setAttribute("gonggaolist",gonggaoService.findTop7());  //设置session
		request.getSession().setAttribute("ptzhaopinlist",ptzhaopinService.findTop7());  //设置session
		request.getSession().setAttribute("dxzhaopinlist",dxzhaopinService.findTop7());  //设置session
		return mapping.findForward("qiantaiHome");  //成功
	}

	// 通过action  method方式  获取所有ptzhaopin
	public ActionForward gonggaoIndexExecute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		
		String findinfo=request.getParameter("findinfo");
		if(findinfo!=null)
			findinfo=URLDecoder.decode(findinfo,"UTF-8");
		else
			findinfo="";
		request.getSession().setAttribute("findinfo",findinfo);
		
		String pagenumber=request.getParameter("pagenumber");
		if(pagenumber==null) pagenumber="1";
		Page p=PageUtil.createPage(10,gonggaoService.findNumsByLikeNameOrId(findinfo),new Integer(pagenumber));
		
		request.getSession().setAttribute("pagenumber",p.getCurrentPage());
		request.getSession().setAttribute("maxpagenumber",p.getTotalPage());
		request.getSession().setAttribute("gonggaolist",gonggaoService.gonggaoLikeNameOrId(findinfo,p));  //设置session
		return mapping.findForward("qiantaiGonggaoMana");  //成功
	}
	//公告信息查看
	public ActionForward gonggaoLookExecute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		String gonggaoid=request.getParameter("gonggaoid");
		Gonggao item=gonggaoService.gonggaoByID(Integer.parseInt(gonggaoid));
		item.setLooknum(item.getLooknum()+1);
		gonggaoService.gonggaoModify(item);
		request.getSession().setAttribute("gonggaolook",item);  //设置session
		return mapping.findForward("qiantaiGonggaoLook");  //成功
	}
	
	// 通过action  method方式  获取所有ptzhaopin
	public ActionForward ptzhaopinIndexExecute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		
		PtzhaopinForm ptzhaopinForm = (PtzhaopinForm) form;// TODO Auto-generated method stub
		//decode一次
		String findinfo=request.getParameter("findinfo");
		if(findinfo!=null)
			findinfo=URLDecoder.decode(findinfo,"UTF-8");
		else
			findinfo="";
		request.getSession().setAttribute("findinfo",findinfo);
		
		String pagenumber=request.getParameter("pagenumber");
		if(pagenumber==null) pagenumber="1";
		Page p=PageUtil.createPage(10,ptzhaopinService.findNumsByLikeNameOrId(findinfo),new Integer(pagenumber));
		
		request.getSession().setAttribute("pagenumber",p.getCurrentPage());
		request.getSession().setAttribute("maxpagenumber",p.getTotalPage());
		request.getSession().setAttribute("ptzhaopinlist",ptzhaopinService.ptzhaopinLikeNameOrId(findinfo,p));  //设置session
		return mapping.findForward("qiantaiPtzhaopinMana");  //成功
	}
	
	//招聘信息查看
	public ActionForward ptzhaopinLookExecute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		String ptzhaopinid=request.getParameter("ptzhaopinid");
		Ptzhaopin item=ptzhaopinService.ptzhaopinByID(Integer.parseInt(ptzhaopinid));
		item.setLooksnum(item.getLooksnum()+1);
		ptzhaopinService.ptzhaopinModify(item);
		item.setDwdescr(item.getDwdescr().replaceAll("\n", "<br>"));
		request.getSession().setAttribute("ptzhaopinlook",item);  //设置session
		return mapping.findForward("qiantaiPtzhaopinLook");  //成功
	}
	// 通过action  method方式  获取所有dxzhaopin
	public ActionForward dxzhaopinIndexExecute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		
		DxzhaopinForm dxzhaopinForm = (DxzhaopinForm) form;// TODO Auto-generated method stub
		//decode一次
		String findinfo=request.getParameter("findinfo");
		if(findinfo!=null)
			findinfo=URLDecoder.decode(findinfo,"UTF-8");
		else
			findinfo="";
		request.getSession().setAttribute("findinfo",findinfo);
		
		String pagenumber=request.getParameter("pagenumber");
		if(pagenumber==null) pagenumber="1";
		Page p=PageUtil.createPage(10,dxzhaopinService.findNumsByLikeNameOrId(findinfo),new Integer(pagenumber));
		
		request.getSession().setAttribute("pagenumber",p.getCurrentPage());
		request.getSession().setAttribute("maxpagenumber",p.getTotalPage());
		request.getSession().setAttribute("dxzhaopinlist",dxzhaopinService.dxzhaopinLikeNameOrId(findinfo,p));  //设置session
		return mapping.findForward("qiantaiDxzhaopinMana");  //成功
	}
	
	//招聘信息查看
	public ActionForward dxzhaopinLookExecute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		String dxzhaopinid=request.getParameter("dxzhaopinid");
		Dxzhaopin item=dxzhaopinService.dxzhaopinByID(Integer.parseInt(dxzhaopinid));
		item.setLooknum(item.getLooknum()+1);
		dxzhaopinService.dxzhaopinModify(item);
		item.setCydw(item.getCydw().replaceAll("\n", "<br>"));
		request.getSession().setAttribute("dxzhaopinlook",item);  //设置session
		return mapping.findForward("qiantaiDxzhaopinLook");  //成功
	}
}