/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-16-2016
 * 
 * XDoclet definition:
 * @struts.form name="administratorForm"
 */
public class AdministratorForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** administratorname property */
	private String administratorname;

	/** administratorpwd property */
	private String administratorpwd;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the administratorname.
	 * @return String
	 */
	public String getAdministratorname() {
		return administratorname;
	}

	/** 
	 * Set the administratorname.
	 * @param administratorname The administratorname to set
	 */
	public void setAdministratorname(String administratorname) {
		this.administratorname = administratorname;
	}

	/** 
	 * Returns the administratorpwd.
	 * @return String
	 */
	public String getAdministratorpwd() {
		return administratorpwd;
	}

	/** 
	 * Set the administratorpwd.
	 * @param administratorpwd The administratorpwd to set
	 */
	public void setAdministratorpwd(String administratorpwd) {
		this.administratorpwd = administratorpwd;
	}
}