/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-18-2016
 * 
 * XDoclet definition:
 * @struts.form name="hotelorderForm"
 */
public class HotelorderForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** roomid property */
	private String roomid;

	/** phone property */
	private String phone;

	/** username property */
	private String username;

	/** roomname property */
	private String roomname;

	/** nums property */
	private String nums;

	/** hotelid property */
	private String hotelid;

	/** name property */
	private String name;

	/** roomprice property */
	private String roomprice;

	/** hotelname property */
	private String hotelname;

	/** checkintime property */
	private String checkintime;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the roomid.
	 * @return String
	 */
	public String getRoomid() {
		return roomid;
	}

	/** 
	 * Set the roomid.
	 * @param roomid The roomid to set
	 */
	public void setRoomid(String roomid) {
		this.roomid = roomid;
	}

	/** 
	 * Returns the phone.
	 * @return String
	 */
	public String getPhone() {
		return phone;
	}

	/** 
	 * Set the phone.
	 * @param phone The phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/** 
	 * Returns the roomname.
	 * @return String
	 */
	public String getRoomname() {
		return roomname;
	}

	/** 
	 * Set the roomname.
	 * @param roomname The roomname to set
	 */
	public void setRoomname(String roomname) {
		this.roomname = roomname;
	}

	/** 
	 * Returns the nums.
	 * @return String
	 */
	public String getNums() {
		return nums;
	}

	/** 
	 * Set the nums.
	 * @param nums The nums to set
	 */
	public void setNums(String nums) {
		this.nums = nums;
	}

	/** 
	 * Returns the hotelid.
	 * @return String
	 */
	public String getHotelid() {
		return hotelid;
	}

	/** 
	 * Set the hotelid.
	 * @param hotelid The hotelid to set
	 */
	public void setHotelid(String hotelid) {
		this.hotelid = hotelid;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the roomprice.
	 * @return String
	 */
	public String getRoomprice() {
		return roomprice;
	}

	/** 
	 * Set the roomprice.
	 * @param roomprice The roomprice to set
	 */
	public void setRoomprice(String roomprice) {
		this.roomprice = roomprice;
	}

	/** 
	 * Returns the hotelname.
	 * @return String
	 */
	public String getHotelname() {
		return hotelname;
	}

	/** 
	 * Set the hotelname.
	 * @param hotelname The hotelname to set
	 */
	public void setHotelname(String hotelname) {
		this.hotelname = hotelname;
	}

	/** 
	 * Returns the checkintime.
	 * @return String
	 */
	public String getCheckintime() {
		return checkintime;
	}

	/** 
	 * Set the checkintime.
	 * @param checkintime The checkintime to set
	 */
	public void setCheckintime(String checkintime) {
		this.checkintime = checkintime;
	}
}