/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-18-2016
 * 
 * XDoclet definition:
 * @struts.form name="spotorderForm"
 */
public class SpotorderForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** spotid property */
	private String spotid;

	/** phone property */
	private String phone;

	/** username property */
	private String username;

	/** totalprice property */
	private String totalprice;

	/** nums property */
	private String nums;

	/** name property */
	private String name;

	/** tratime property */
	private String tratime;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the spotid.
	 * @return String
	 */
	public String getSpotid() {
		return spotid;
	}

	/** 
	 * Set the spotid.
	 * @param spotid The spotid to set
	 */
	public void setSpotid(String spotid) {
		this.spotid = spotid;
	}

	/** 
	 * Returns the phone.
	 * @return String
	 */
	public String getPhone() {
		return phone;
	}

	/** 
	 * Set the phone.
	 * @param phone The phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/** 
	 * Returns the totalprice.
	 * @return String
	 */
	public String getTotalprice() {
		return totalprice;
	}

	/** 
	 * Set the totalprice.
	 * @param totalprice The totalprice to set
	 */
	public void setTotalprice(String totalprice) {
		this.totalprice = totalprice;
	}

	/** 
	 * Returns the nums.
	 * @return String
	 */
	public String getNums() {
		return nums;
	}

	/** 
	 * Set the nums.
	 * @param nums The nums to set
	 */
	public void setNums(String nums) {
		this.nums = nums;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the tratime.
	 * @return String
	 */
	public String getTratime() {
		return tratime;
	}

	/** 
	 * Set the tratime.
	 * @param tratime The tratime to set
	 */
	public void setTratime(String tratime) {
		this.tratime = tratime;
	}
}