/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-16-2016
 * 
 * XDoclet definition:
 * @struts.form name="viewspotForm"
 */
public class ViewspotForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** spotremark property */
	private String spotremark;

	/** sportimage property */
	private String sportimage;

	/** spotprice property */
	private String spotprice;

	/** spotname property */
	private String spotname;

	/** spotaddr property */
	private String spotaddr;

	/** spotdescr property */
	private String spotdescr;

	/** spotcity property */
	private String spotcity;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the spotremark.
	 * @return String
	 */
	public String getSpotremark() {
		return spotremark;
	}

	/** 
	 * Set the spotremark.
	 * @param spotremark The spotremark to set
	 */
	public void setSpotremark(String spotremark) {
		this.spotremark = spotremark;
	}

	/** 
	 * Returns the sportimage.
	 * @return String
	 */
	public String getSportimage() {
		return sportimage;
	}

	/** 
	 * Set the sportimage.
	 * @param sportimage The sportimage to set
	 */
	public void setSportimage(String sportimage) {
		this.sportimage = sportimage;
	}

	/** 
	 * Returns the spotprice.
	 * @return String
	 */
	public String getSpotprice() {
		return spotprice;
	}

	/** 
	 * Set the spotprice.
	 * @param spotprice The spotprice to set
	 */
	public void setSpotprice(String spotprice) {
		this.spotprice = spotprice;
	}

	/** 
	 * Returns the spotname.
	 * @return String
	 */
	public String getSpotname() {
		return spotname;
	}

	/** 
	 * Set the spotname.
	 * @param spotname The spotname to set
	 */
	public void setSpotname(String spotname) {
		this.spotname = spotname;
	}

	/** 
	 * Returns the spotaddr.
	 * @return String
	 */
	public String getSpotaddr() {
		return spotaddr;
	}

	/** 
	 * Set the spotaddr.
	 * @param spotaddr The spotaddr to set
	 */
	public void setSpotaddr(String spotaddr) {
		this.spotaddr = spotaddr;
	}

	/** 
	 * Returns the spotdescr.
	 * @return String
	 */
	public String getSpotdescr() {
		return spotdescr;
	}

	/** 
	 * Set the spotdescr.
	 * @param spotdescr The spotdescr to set
	 */
	public void setSpotdescr(String spotdescr) {
		this.spotdescr = spotdescr;
	}

	/** 
	 * Returns the spotcity.
	 * @return String
	 */
	public String getSpotcity() {
		return spotcity;
	}

	/** 
	 * Set the spotcity.
	 * @param spotcity The spotcity to set
	 */
	public void setSpotcity(String spotcity) {
		this.spotcity = spotcity;
	}
}