/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import java.net.URLDecoder;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.pojo.Administrator;
import com.service.AdministratorService;
import com.struts.form.AdministratorForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-16-2016
 * 
 * XDoclet definition:
 * @struts.action path="/administrator" name="administratorForm" input="/form/administrator.jsp" scope="request" validate="true"
 */
public class AdministratorAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	// 依赖注入 AdministratorService
	private AdministratorService administratorService;

	public AdministratorService getAdministratorService() {
		return administratorService;
	}

	public void setAdministratorService(AdministratorService administratorService) {
		this.administratorService = administratorService;
	}
	
	// 通过用户密码 验证登录  dwr实现AJAX方式 验证登录
	public String administratorLogin(String username,String password)
	{
		//ActionContext actionContext = ActionContext.APPLICATION_SCOPE
		
		Administrator user=new Administrator(username,password);
		if(administratorService.administratorLogin(user))
			return "success";
    	return "fail";
	}
	
	// 通过action  method方式添加用户
		public ActionForward administratorAddExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			AdministratorForm administratorForm = (AdministratorForm) form;// TODO Auto-generated method stub
			// 乱码问题
			Administrator user=new Administrator(administratorForm.getAdministratorname(),administratorForm.getAdministratorpwd());
			administratorService.administratorAdd(user);
			//System.out.println(user.getUsername());
			request.getSession().setAttribute("adminlist",administratorService.administratorLikeNameOrId(""));  //设置session
			return mapping.findForward("administratorMana");  //成功
		}
		
		// 通过action  method方式删除用户
		public ActionForward administratorDeleteExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			String adminid=request.getParameter("adminid");
			Administrator user=new Administrator();
			user.setAdminid(Integer.parseInt(adminid));
			administratorService.administratorDelete(user);
			request.getSession().setAttribute("adminlist",administratorService.administratorLikeNameOrId(""));  //设置session
			return mapping.findForward("administratorMana");  //成功
		}
		
		// 通过action  method方式修改用户之前
		public ActionForward administratorBeforeModifyExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			String adminid=request.getParameter("adminid");
			Administrator user=administratorService.administratorByID(Integer.parseInt(adminid));
			request.getSession().setAttribute("adminmodifyinfo",user);  //设置session
			return mapping.findForward("administratorBeforeModify");  //成功
		}
		
		// 通过action  method方式修改用户
		public ActionForward administratorModifyExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			AdministratorForm administratorForm = (AdministratorForm) form;// TODO Auto-generated method stub
			String adminid=request.getParameter("adminid");
			Administrator user=new Administrator(administratorForm.getAdministratorname(),administratorForm.getAdministratorpwd());
			user.setAdminid(Integer.parseInt(adminid));
			//System.out.println(user.getUsername());
			administratorService.administratorModify(user);
			request.getSession().setAttribute("adminlist",administratorService.administratorLikeNameOrId(""));  //设置session
			return mapping.findForward("administratorMana");  //成功
		}
		
		
		// 通过action  method方式  获取所有用户
		public ActionForward administratorFindExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			
			AdministratorForm administratorForm = (AdministratorForm) form;// TODO Auto-generated method stub
			//decode一次
			String nameorid=request.getParameter("adminfindnfo");
			if(nameorid!=null)
				nameorid=URLDecoder.decode(nameorid,"UTF-8");
			else
				nameorid="";
			request.getSession().setAttribute("adminlist",administratorService.administratorLikeNameOrId(nameorid));  //设置session
			return mapping.findForward("administratorMana");  //成功
		}
}