/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import java.net.URLDecoder;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.pojo.Goodtype;
import com.service.GoodtypeService;
import com.struts.form.GoodtypeForm;
public class GoodtypeAction extends DispatchAction {
	// 依赖注入 GoodtypeService
		private GoodtypeService goodtypeService;

		public GoodtypeService getGoodtypeService() {
			return goodtypeService;
		}

		public void setGoodtypeService(GoodtypeService goodtypeService) {
			this.goodtypeService = goodtypeService;
		}
		
		public Object[][] getGoodType()
		{
			// 获得产品类别
			List<Goodtype> list=goodtypeService.goodtypeAll();
			Object[][] result=new Object[list.size()][2];
			for(int i=0;i<list.size();++i) {
				result[i][0]=list.get(i).getTypeid();
				result[i][1]=list.get(i).getTypename();
			}
			return result;
		}
		
		//dwr添加类别
		public void goodtypeAdd(String typename,String typedescr)
		{
			Goodtype user=new Goodtype(typename,typedescr);
			goodtypeService.goodtypeAdd(user);
		}
		
		//dwr修改类别
		public void goodtypeEdit(String id,String typename,String typedescr)
		{
			Goodtype user=goodtypeService.goodtypeByID(new Integer(id));
			user.setTypedescr(typedescr);
			user.setTypename(typename);
			goodtypeService.goodtypeModify(user);
		}
		
		// 通过action  method方式添加用户
		public ActionForward goodtypeAddExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			GoodtypeForm goodtypeForm = (GoodtypeForm) form;// TODO Auto-generated method stub
			// 乱码问题
			//Goodtype user=new Goodtype(goodtypeForm.getGoodtypename(),goodtypeForm.getGoodtypepwd());
			//goodtypeService.goodtypeAdd(user);
			//System.out.println(user.getUsername());
			//request.getSession().setAttribute("adminlist",goodtypeService.goodtypeLikeNameOrId(""));  //设置session
			return mapping.findForward("goodtypeMana");  //成功
		}
		
		// 通过action  method方式删除用户
		public ActionForward goodtypeDeleteExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			String id=request.getParameter("goodtypeid");
			Goodtype user=new Goodtype();
			user.setTypeid(Integer.parseInt(id));
			goodtypeService.goodtypeDelete(user);
			request.getSession().setAttribute("goodtypelist",goodtypeService.goodtypeAll());  //设置session
			return mapping.findForward("goodtypeMana");  //成功
		}
		
		// 通过action  method方式修改用户之前
		public ActionForward goodtypeBeforeModifyExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			String adminid=request.getParameter("id");
			Goodtype user=goodtypeService.goodtypeByID(Integer.parseInt(adminid));
			request.getSession().setAttribute("adminmodifyinfo",user);  //设置session
			return mapping.findForward("goodtypeBeforeModify");  //成功
		}
		
		// 通过action  method方式修改用户
		public ActionForward goodtypeModifyExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			GoodtypeForm goodtypeForm = (GoodtypeForm) form;// TODO Auto-generated method stub
			String adminid=request.getParameter("goodtypeid");
			//Goodtype user=new Goodtype(goodtypeForm.getGoodtypename(),goodtypeForm.getGoodtypepwd());
			//user.setAdminid(Integer.parseInt(adminid));
			//System.out.println(user.getUsername());
			//goodtypeService.goodtypeModify(user);
			request.getSession().setAttribute("adminlist",goodtypeService.goodtypeAll());  //设置session
			return mapping.findForward("goodtypeMana");  //成功
		}
		
		
		// 通过action  method方式  获取所有用户
		public ActionForward goodtypeAllExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			
			GoodtypeForm goodtypeForm = (GoodtypeForm) form;// TODO Auto-generated method stub
			request.getSession().setAttribute("goodtypelist",goodtypeService.goodtypeAll());  //设置session
			return mapping.findForward("goodtypeMana");  //成功
		}
}