/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.pojo.Goodcomment;
import com.service.GoodcommentService;
import com.struts.form.GoodcommentForm;
import com.struts.form.GoodcommentForm;
import com.util.StringUtil;

/** 
 * MyEclipse Struts
 * Creation date: 05-21-2016
 * 
 * XDoclet definition:
 * @struts.action path="/goodcomment" name="goodcommentForm" input="/form/goodcomment.jsp" scope="request" validate="true"
 */
public class GoodcommentAction extends DispatchAction {
	// 依赖注入 GoodcommentService
		private GoodcommentService goodcommentService;

		public GoodcommentService getGoodcommentService() {
			return goodcommentService;
		}

		public void setGoodcommentService(GoodcommentService goodcommentService) {
			this.goodcommentService = goodcommentService;
		}
		
		
		// 通过action  method方式添加用户
		public ActionForward goodcommentAddExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			GoodcommentForm goodcommentForm = (GoodcommentForm) form;// TODO Auto-generated method stub
			// 乱码问题
			Goodcomment user=new Goodcomment(new Integer(goodcommentForm.getGoodid()),new Integer(goodcommentForm.getUserid()),goodcommentForm.getUsername(),goodcommentForm.getContent(),StringUtil.getTimestampFromDate(new Date()));
			goodcommentService.goodcommentAdd(user);
			return mapping.findForward("goodcommentMana");  //成功
		}
		
		// 通过action  method方式删除用户
		public ActionForward goodcommentDeleteExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			String id=request.getParameter("goodcommentid");
			Goodcomment user=new Goodcomment();
			user.setId(new Integer(id));
			goodcommentService.goodcommentDelete(user);
			return mapping.findForward("goodcommentMana");  //成功
		}
}