/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import java.net.URLDecoder;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.pojo.Goodorderinfo;
import com.service.GoodorderinfoService;
import com.struts.form.GoodorderinfoForm;

public class GoodorderinfoAction extends DispatchAction {
	// 依赖注入 GoodorderinfoService
		private GoodorderinfoService goodorderinfoService;

		public GoodorderinfoService getGoodorderinfoService() {
			return goodorderinfoService;
		}

		public void setGoodorderinfoService(GoodorderinfoService goodorderinfoService) {
			this.goodorderinfoService = goodorderinfoService;
		}
		
		
		// 通过action  method方式删除用户
		public ActionForward goodorderinfoDeleteExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			
			return mapping.findForward("goodorderinfoMana");  //成功
		}
		
		// 通过action  method方式  获取所有用户
		public ActionForward goodorderinfoFindExecute(ActionMapping mapping, ActionForm form,
				HttpServletRequest request, HttpServletResponse response) throws Exception{
			//decode一次
			String nameorid=request.getParameter("goodorderid");
			request.getSession().setAttribute("goodorderinfolist",goodorderinfoService.goodorderinfoAll(nameorid));  //设置session
			return mapping.findForward("goodorderinfoMana");  //成功
		}
}