/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import java.net.URLDecoder;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.pojo.Hotelorder;
import com.service.HotelorderService;
import com.struts.form.HotelorderForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-18-2016
 * 
 * XDoclet definition:
 * @struts.action path="/hotelorder" name="hotelorderForm" input="/form/hotelorder.jsp" scope="request" validate="true"
 */
public class HotelorderAction extends DispatchAction {
	// 依赖注入 HotelorderService
	private HotelorderService hotelorderService;

	public HotelorderService getHotelorderService() {
		return hotelorderService;
	}

	public void setHotelorderService(HotelorderService hotelorderService) {
		this.hotelorderService = hotelorderService;
	}
	
	
	// 通过action  method方式删除用户
	public ActionForward hotelorderDeleteExecute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		String hotelorderid=request.getParameter("hotelorderid");
		Hotelorder user=new Hotelorder();
		user.setOrderid(hotelorderid);
		hotelorderService.hotelorderDelete(user);
		String nameorid=request.getParameter("hotelorderfindnfo");
		String s1=request.getParameter("starttime");
		String s2=request.getParameter("endtime");
		if(nameorid!=null)
			nameorid=URLDecoder.decode(nameorid,"UTF-8");
		else
			nameorid="";
		if(s1==null||s2==null)
		{
			Format format = new SimpleDateFormat("yyyy-MM-dd");
			Date date=new Date();
			Calendar calendar=new  GregorianCalendar(); 
		    calendar.setTime(date); 
		    calendar.add(calendar.DATE,1);//把日期往后增加一天.整数往后推,负数往前移动 
		    date=calendar.getTime();   //这个时间就是日期往后推一天的结果 
			s2=format.format(date);
			calendar.add(calendar.DATE,-31);//把日期往后增加一天.整数往后推,负数往前移动 
		    date=calendar.getTime();   //这个时间就是日期往后推一天的结果 
			s1=format.format(date);
		}
		request.getSession().setAttribute("starttime", s1);
		request.getSession().setAttribute("endtime", s2);
		request.getSession().setAttribute("hotelorderfindnfo", nameorid);
		request.getSession().setAttribute("hotelorderlist",hotelorderService.hotelorderLikeNameOrId(nameorid,s1,s2));  //设置session
		return mapping.findForward("hotelorderMana");  //成功
	}
	
	// 通过action  method方式  获取所有用户
	public ActionForward hotelorderFindExecute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		//decode一次
		String nameorid=request.getParameter("hotelorderfindnfo");
		String s1=request.getParameter("starttime");
		String s2=request.getParameter("endtime");
		if(nameorid!=null)
			nameorid=URLDecoder.decode(nameorid,"UTF-8");
		else
			nameorid="";
		if(s1==null||s2==null)
		{
			Format format = new SimpleDateFormat("yyyy-MM-dd");
			Date date=new Date();
			Calendar calendar=new  GregorianCalendar(); 
		    calendar.setTime(date); 
		    calendar.add(calendar.DATE,1);//把日期往后增加一天.整数往后推,负数往前移动 
		    date=calendar.getTime();   //这个时间就是日期往后推一天的结果 
			s2=format.format(date);
			calendar.add(calendar.DATE,-31);//把日期往后增加一天.整数往后推,负数往前移动 
		    date=calendar.getTime();   //这个时间就是日期往后推一天的结果 
			s1=format.format(date);
		}
		request.getSession().setAttribute("starttime", s1);
		request.getSession().setAttribute("endtime", s2);
		request.getSession().setAttribute("hotelorderfindnfo", nameorid);
		request.getSession().setAttribute("hotelorderlist",hotelorderService.hotelorderLikeNameOrId(nameorid,s1,s2));  //设置session
		return mapping.findForward("hotelorderMana");  //成功
	}
}