/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.pojo.Hotelcomment;
import com.service.HotelcommentService;
import com.struts.form.HotelcommentForm;
import com.util.StringUtil;

/** 
 * MyEclipse Struts
 * Creation date: 05-20-2016
 * 
 * XDoclet definition:
 * @struts.action path="/hotelcomment" name="hotelcommentForm" input="/form/hotelcomment.jsp" scope="request" validate="true"
 */
public class HotelcommentAction extends DispatchAction {
	// 依赖注入 HotelcommentService
	private HotelcommentService hotelcommentService;

	public HotelcommentService getHotelcommentService() {
		return hotelcommentService;
	}

	public void setHotelcommentService(HotelcommentService hotelcommentService) {
		this.hotelcommentService = hotelcommentService;
	}
	
	
	// 通过action  method方式添加用户
	public ActionForward hotelcommentAddExecute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		HotelcommentForm hotelcommentForm = (HotelcommentForm) form;// TODO Auto-generated method stub
		// 乱码问题
		Hotelcomment user=new Hotelcomment(new Integer(hotelcommentForm.getHotelid()),new Integer(hotelcommentForm.getUserid()),hotelcommentForm.getUsername(),hotelcommentForm.getContent(),StringUtil.getTimestampFromDate(new Date()));
		hotelcommentService.hotelcommentAdd(user);
		return mapping.findForward("hotelcommentMana");  //成功
	}
	
	// 通过action  method方式删除用户
	public ActionForward hotelcommentDeleteExecute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		String id=request.getParameter("hotelcommentid");
		Hotelcomment user=new Hotelcomment();
		user.setId(new Integer(id));
		hotelcommentService.hotelcommentDelete(user);
		return mapping.findForward("hotelcommentMana");  //成功
	}
}