/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import java.net.URLDecoder;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.pojo.Luntanhuati;
import com.service.LuntanhuatiService;
import com.struts.form.LuntanhuatiForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-21-2016
 * 
 * XDoclet definition:
 * @struts.action path="/luntanhuati" name="luntanhuatiForm" input="/form/luntanhuati.jsp" scope="request" validate="true"
 */
public class LuntanhuatiAction extends DispatchAction {
	private LuntanhuatiService luntanhuatiService;

	public LuntanhuatiService getLuntanhuatiService() {
		return luntanhuatiService;
	}

	public void setLuntanhuatiService(LuntanhuatiService luntanhuatiService) {
		this.luntanhuatiService = luntanhuatiService;
	}
	// 通过action  method方式  获取所有用户
	public ActionForward luntanhuatiListExecute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		//decode一次
		String findinfo=request.getParameter("findinfo");
		if(findinfo!=null)
			findinfo=URLDecoder.decode(findinfo,"UTF-8");
		else
			findinfo="";
		
		request.getSession().setAttribute("findinfo",findinfo);
		
		request.getSession().setAttribute("luntanhuatilist",luntanhuatiService.LuntanhuatiAll(findinfo));  //设置session
		return mapping.findForward("luntanhuatiListMana");  //成功
	}
	
	//查看单个景点信息
	public ActionForward luntanhuatiLookExecute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		//decode一次
		String id=request.getParameter("luntanhuatiid");
		//System.out.println(spotid);
		Luntanhuati luntanhuatiinfo=luntanhuatiService.getLuntanhuati(id);
		luntanhuatiinfo.setLooknum(luntanhuatiinfo.getLooknum()+1);
		luntanhuatiService.modifyLuntanhuati(luntanhuatiinfo);
		request.getSession().setAttribute("luntanhuatiinfo",luntanhuatiinfo);  //设置session  getRoomtypeByLuntanhuatiid
		return mapping.findForward("luntanhuatiInfoMana");  //成功
	}
}