/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import java.net.URLDecoder;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.pojo.Spotcomment;
import com.service.SpotcommentService;
import com.struts.form.SpotcommentForm;
import com.struts.form.SpotcommentForm;
import com.util.StringUtil;

/** 
 * MyEclipse Struts
 * Creation date: 05-20-2016
 * 
 * XDoclet definition:
 * @struts.action path="/spotcomment" name="spotcommentForm" input="/form/spotcomment.jsp" scope="request" validate="true"
 */
public class SpotcommentAction extends DispatchAction {
	// 依赖注入 SpotcommentService
		private SpotcommentService spotcommentService;

		public SpotcommentService getSpotcommentService() {
			return spotcommentService;
		}

		public void setSpotcommentService(SpotcommentService spotcommentService) {
			this.spotcommentService = spotcommentService;
		}
		
		
		// 通过action  method方式添加用户
			public ActionForward spotcommentAddExecute(ActionMapping mapping, ActionForm form,
					HttpServletRequest request, HttpServletResponse response) throws Exception{
				SpotcommentForm spotcommentForm = (SpotcommentForm) form;// TODO Auto-generated method stub
				// 乱码问题
				Spotcomment user=new Spotcomment(new Integer(spotcommentForm.getSpotid()),new Integer(spotcommentForm.getUserid()),spotcommentForm.getUsername(),spotcommentForm.getContent(),StringUtil.getTimestampFromDate(new Date()));
				spotcommentService.spotcommentAdd(user);
				return mapping.findForward("spotcommentMana");  //成功
			}
			
			// 通过action  method方式删除用户
			public ActionForward spotcommentDeleteExecute(ActionMapping mapping, ActionForm form,
					HttpServletRequest request, HttpServletResponse response) throws Exception{
				String id=request.getParameter("spotcommentid");
				Spotcomment user=new Spotcomment();
				user.setId(new Integer(id));
				spotcommentService.spotcommentDelete(user);
				return mapping.findForward("spotcommentMana");  //成功
			}
}