/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-27-2016
 * 
 * XDoclet definition:
 * @struts.form name="academyForm"
 */
public class AcademyForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** academyname property */
	private String academyname;
	private String academydescr;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the academyname.
	 * @return String
	 */
	public String getAcademyname() {
		return academyname;
	}

	/** 
	 * Set the academyname.
	 * @param academyname The academyname to set
	 */
	public void setAcademyname(String academyname) {
		this.academyname = academyname;
	}

	public String getAcademydescr() {
		return academydescr;
	}

	public void setAcademydescr(String academydescr) {
		this.academydescr = academydescr;
	}
}