/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-27-2016
 * 
 * XDoclet definition:
 * @struts.form name="classroomForm"
 */
public class ClassroomForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** classname property */
	private String classid;
	private String classname;
	private String classdescr;
	/** academy property */
	private String academyid;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the classname.
	 * @return String
	 */
	public String getClassname() {
		return classname;
	}

	/** 
	 * Set the classname.
	 * @param classname The classname to set
	 */
	public void setClassname(String classname) {
		this.classname = classname;
	}


	public String getClassdescr() {
		return classdescr;
	}

	public void setClassdescr(String classdescr) {
		this.classdescr = classdescr;
	}

	public String getClassid() {
		return classid;
	}

	public void setClassid(String classid) {
		this.classid = classid;
	}

	public String getAcademyid() {
		return academyid;
	}

	public void setAcademyid(String academyid) {
		this.academyid = academyid;
	}
}