/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-28-2016
 * 
 * XDoclet definition:
 * @struts.form name="puzhaopinForm"
 */
public class PtzhaopinForm extends ActionForm {
	/*
	 * Generated fields
	 */
	private String xingzhi;
	/** endtime property */
	private String endtime;
	
	/** phone property */
	private String phone;

	/** starttime property */
	private String starttime;

	/** zpaddr property */
	private String zpaddr;

	/** chuanzhen property */
	private String chuanzhen;

	/** gangwei property */
	private String gangwei;

	/** xueli property */
	private String xueli;

	/** hangye property */
	private String hangye;

	/** email property */
	private String email;

	/** address property */
	private String address;

	/** nums property */
	private String nums;

	/** homeurl property */
	private String homeurl;

	/** zhuanye property */
	private String zhuanye;

	/** name property */
	private String name;

	/** shenfe property */
	private String shenfe;

	/** gangweidescr property */
	private String gangweidescr;

	/** dwdescr property */
	private String dwdescr;

	private String title;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the endtime.
	 * @return String
	 */
	public String getEndtime() {
		return endtime;
	}

	/** 
	 * Set the endtime.
	 * @param endtime The endtime to set
	 */
	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	/** 
	 * Returns the phone.
	 * @return String
	 */
	public String getPhone() {
		return phone;
	}

	/** 
	 * Set the phone.
	 * @param phone The phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/** 
	 * Returns the starttime.
	 * @return String
	 */
	public String getStarttime() {
		return starttime;
	}

	/** 
	 * Set the starttime.
	 * @param starttime The starttime to set
	 */
	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	/** 
	 * Returns the zpaddr.
	 * @return String
	 */
	public String getZpaddr() {
		return zpaddr;
	}

	/** 
	 * Set the zpaddr.
	 * @param zpaddr The zpaddr to set
	 */
	public void setZpaddr(String zpaddr) {
		this.zpaddr = zpaddr;
	}

	/** 
	 * Returns the chuanzhen.
	 * @return String
	 */
	public String getChuanzhen() {
		return chuanzhen;
	}

	/** 
	 * Set the chuanzhen.
	 * @param chuanzhen The chuanzhen to set
	 */
	public void setChuanzhen(String chuanzhen) {
		this.chuanzhen = chuanzhen;
	}

	/** 
	 * Returns the gangwei.
	 * @return String
	 */
	public String getGangwei() {
		return gangwei;
	}

	/** 
	 * Set the gangwei.
	 * @param gangwei The gangwei to set
	 */
	public void setGangwei(String gangwei) {
		this.gangwei = gangwei;
	}

	/** 
	 * Returns the xueli.
	 * @return String
	 */
	public String getXueli() {
		return xueli;
	}

	/** 
	 * Set the xueli.
	 * @param xueli The xueli to set
	 */
	public void setXueli(String xueli) {
		this.xueli = xueli;
	}

	/** 
	 * Returns the hangye.
	 * @return String
	 */
	public String getHangye() {
		return hangye;
	}

	/** 
	 * Set the hangye.
	 * @param hangye The hangye to set
	 */
	public void setHangye(String hangye) {
		this.hangye = hangye;
	}

	/** 
	 * Returns the email.
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/** 
	 * Set the email.
	 * @param email The email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/** 
	 * Returns the address.
	 * @return String
	 */
	public String getAddress() {
		return address;
	}

	/** 
	 * Set the address.
	 * @param address The address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/** 
	 * Returns the nums.
	 * @return String
	 */
	public String getNums() {
		return nums;
	}

	/** 
	 * Set the nums.
	 * @param nums The nums to set
	 */
	public void setNums(String nums) {
		this.nums = nums;
	}

	/** 
	 * Returns the homeurl.
	 * @return String
	 */
	public String getHomeurl() {
		return homeurl;
	}

	/** 
	 * Set the homeurl.
	 * @param homeurl The homeurl to set
	 */
	public void setHomeurl(String homeurl) {
		this.homeurl = homeurl;
	}

	/** 
	 * Returns the zhuanye.
	 * @return String
	 */
	public String getZhuanye() {
		return zhuanye;
	}

	/** 
	 * Set the zhuanye.
	 * @param zhuanye The zhuanye to set
	 */
	public void setZhuanye(String zhuanye) {
		this.zhuanye = zhuanye;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the shenfe.
	 * @return String
	 */
	public String getShenfe() {
		return shenfe;
	}

	/** 
	 * Set the shenfe.
	 * @param shenfe The shenfe to set
	 */
	public void setShenfe(String shenfe) {
		this.shenfe = shenfe;
	}

	/** 
	 * Returns the gangweidescr.
	 * @return String
	 */
	public String getGangweidescr() {
		return gangweidescr;
	}

	/** 
	 * Set the gangweidescr.
	 * @param gangweidescr The gangweidescr to set
	 */
	public void setGangweidescr(String gangweidescr) {
		this.gangweidescr = gangweidescr;
	}

	/** 
	 * Returns the dwdescr.
	 * @return String
	 */
	public String getDwdescr() {
		return dwdescr;
	}

	/** 
	 * Set the dwdescr.
	 * @param dwdescr The dwdescr to set
	 */
	public void setDwdescr(String dwdescr) {
		this.dwdescr = dwdescr;
	}

	public String getXingzhi() {
		return xingzhi;
	}

	public void setXingzhi(String xingzhi) {
		this.xingzhi = xingzhi;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
}