/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-27-2016
 * 
 * XDoclet definition:
 * @struts.form name="teacherForm"
 */
public class TeacherForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** sex property */
	private String sex;

	/** phone property */
	private String phone;

	/** teaid property */
	private String teaid;

	/** direction property */
	private String direction;

	/** idcard property */
	private String idcard;

	/** academy property */
	private String academyid;

	/** qqid property */
	private String qqid;

	/** pwd property */
	private String pwd;

	/** level property */
	private String level;

	/** name property */
	private String name;

	/** reserved2 property */
	private String reserved2;

	/** schooltime property */
	private String schooltime;

	/** reserved1 property */
	private String reserved1;

	/** roletype property */
	private String roletype;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the sex.
	 * @return String
	 */
	public String getSex() {
		return sex;
	}

	/** 
	 * Set the sex.
	 * @param sex The sex to set
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/** 
	 * Returns the phone.
	 * @return String
	 */
	public String getPhone() {
		return phone;
	}

	/** 
	 * Set the phone.
	 * @param phone The phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/** 
	 * Returns the teaid.
	 * @return String
	 */
	public String getTeaid() {
		return teaid;
	}

	/** 
	 * Set the teaid.
	 * @param teaid The teaid to set
	 */
	public void setTeaid(String teaid) {
		this.teaid = teaid;
	}

	/** 
	 * Returns the direction.
	 * @return String
	 */
	public String getDirection() {
		return direction;
	}

	/** 
	 * Set the direction.
	 * @param direction The direction to set
	 */
	public void setDirection(String direction) {
		this.direction = direction;
	}

	/** 
	 * Returns the idcard.
	 * @return String
	 */
	public String getIdcard() {
		return idcard;
	}

	/** 
	 * Set the idcard.
	 * @param idcard The idcard to set
	 */
	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}


	/** 
	 * Returns the qqid.
	 * @return String
	 */
	public String getQqid() {
		return qqid;
	}

	/** 
	 * Set the qqid.
	 * @param qqid The qqid to set
	 */
	public void setQqid(String qqid) {
		this.qqid = qqid;
	}

	/** 
	 * Returns the pwd.
	 * @return String
	 */
	public String getPwd() {
		return pwd;
	}

	/** 
	 * Set the pwd.
	 * @param pwd The pwd to set
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/** 
	 * Returns the level.
	 * @return String
	 */
	public String getLevel() {
		return level;
	}

	/** 
	 * Set the level.
	 * @param level The level to set
	 */
	public void setLevel(String level) {
		this.level = level;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the reserved2.
	 * @return String
	 */
	public String getReserved2() {
		return reserved2;
	}

	/** 
	 * Set the reserved2.
	 * @param reserved2 The reserved2 to set
	 */
	public void setReserved2(String reserved2) {
		this.reserved2 = reserved2;
	}

	/** 
	 * Returns the schooltime.
	 * @return String
	 */
	public String getSchooltime() {
		return schooltime;
	}

	/** 
	 * Set the schooltime.
	 * @param schooltime The schooltime to set
	 */
	public void setSchooltime(String schooltime) {
		this.schooltime = schooltime;
	}

	/** 
	 * Returns the reserved1.
	 * @return String
	 */
	public String getReserved1() {
		return reserved1;
	}

	/** 
	 * Set the reserved1.
	 * @param reserved1 The reserved1 to set
	 */
	public void setReserved1(String reserved1) {
		this.reserved1 = reserved1;
	}

	/** 
	 * Returns the roletype.
	 * @return String
	 */
	public String getRoletype() {
		return roletype;
	}

	/** 
	 * Set the roletype.
	 * @param roletype The roletype to set
	 */
	public void setRoletype(String roletype) {
		this.roletype = roletype;
	}

	public String getAcademyid() {
		return academyid;
	}

	public void setAcademyid(String academyid) {
		this.academyid = academyid;
	}
}